Shellcheck

diff --git a/lazysar b/lazysar
--- a/lazysar
+++ b/lazysar
@@ -1,114 +1,110 @@
 #!/usr/bin/env bash
 
-SCRIPT_PATH=$(readlink -f $0)
+SCRIPT_PATH=$(readlink -f "$0")
 SCRIPT_DIR=${SCRIPT_PATH%/*}
 RUN_DIR=/var/run/lazysar
 RUN_CMDS="$RUN_DIR/${USER}-commands"
 DEFAULTS_FILE="$HOME/.config/lazysar/defaults"
 if [ ! -f "$DEFAULTS_FILE" ]; then
-    DEFAULTS_FILE="$SCRIPT_DIR/defaults"
+  DEFAULTS_FILE="$SCRIPT_DIR/defaults"
 fi
 PRESETS_FILE="$HOME/.config/lazysar/presets.json"
 if [ ! -f "$PRESETS_FILE" ]; then
-    PRESETS_FILE="$SCRIPT_DIR/presets.json"
+  PRESETS_FILE="$SCRIPT_DIR/presets.json"
 fi
 
 function check_zellij() {
-    if ! command -v zellij >/dev/null; then
-        echo "This command requires zellij to be installed!"
-        exit 1
-    fi
+  if ! command -v zellij >/dev/null; then
+    echo "This command requires zellij to be installed!"
+    exit 1
+  fi
 }
 
 if [ "$1" = "panel" ]; then
+  shift
+  check_zellij
+  mkdir -p $RUN_DIR
+
+  if [[ $1 =~ ^- ]]; then
+    LAYOUT=basic
+  else
+    LAYOUT=${1-basic}
     shift
-    check_zellij
-    mkdir -p $RUN_DIR
+  fi
 
-    if [[ "$1" =~ ^- ]]; then
-        LAYOUT=basic
-    else
-        LAYOUT=${1-basic}
-        shift
-    fi
+  if [ $# -ne 0 ]; then
+    printf '%s ' "$@" | sed 's/ $/\n/' >"$RUN_CMDS"
+  else
+    cat "$DEFAULTS_FILE" >"$RUN_CMDS"
+  fi
 
-    if [ $# -ne 0 ]; then
-        printf '%s ' "$@" | sed 's/ $/\n/' > $RUN_CMDS
-    else
-        cat $DEFAULTS_FILE > $RUN_CMDS
-    fi
+  LAYOUT_PATH="$HOME/.config/zellij/layouts/${LAYOUT}.kdl"
+  if [[ ! -f $LAYOUT_PATH ]]; then
+    LAYOUT_PATH="$SCRIPT_DIR/layouts/${LAYOUT}.kdl"
+  fi
+  if [[ ! -f $LAYOUT_PATH ]]; then
+    echo "Cannot find zellij layout $LAYOUT_PATH"
+    exit 1
+  fi
 
-    LAYOUT_PATH="$HOME/.config/zellij/layouts/${LAYOUT}.kdl"
-    if [[ ! -f "$LAYOUT_PATH" ]]; then
-        LAYOUT_PATH="$SCRIPT_DIR/layouts/${LAYOUT}.kdl"
-    fi
-    if [[ ! -f "$LAYOUT_PATH" ]]; then
-        echo "Cannot find zellij layout $LAYOUT_PATH"
-        exit 1
-    fi
-
-    SESSION=lazysar-panel-$LAYOUT
-    if zellij list-sessions 2>/dev/null | grep -q $SESSION; then
-        zellij attach -f $SESSION
-    else
-        zellij -s $SESSION -l "$LAYOUT_PATH"
-    fi
-    exit
+  zellij -l "$LAYOUT_PATH"
+  exit
 fi
 
 if [ "$1" = "client" ]; then
-    shift
-    touch $RUN_CMDS
+  shift
+  touch "$RUN_CMDS"
 
-    while read COMMANDS; do
-        if [ "$COMMANDS" == "STOP" ]; then
-            break
-        fi
-        eval lazysar "$@" "--watch='$RUN_CMDS' --title='' $COMMANDS"
-    done < <(tail -n 1 -f $RUN_CMDS 2>/dev/null)
-    exit
+  while read -r COMMANDS; do
+    if [ "$COMMANDS" == "STOP" ]; then
+      break
+    fi
+    # shellcheck disable=SC2294
+    eval lazysar "$@" "--watch='$RUN_CMDS' --title='' $COMMANDS"
+  done < <(tail -n 1 -f "$RUN_CMDS" 2>/dev/null)
+  exit
 fi
 
 function stop_clients() {
-    echo STOP > $RUN_CMDS
-    zellij action close-tab
+  echo STOP >"$RUN_CMDS"
+  zellij action close-tab
 }
 
 if [ "$1" = "cmd" ]; then
-    shift
-    sleep 2
-    LAST_COMMAND=$(tail -1 $RUN_CMDS)
-    trap stop_clients EXIT
-    if command -v rlwrap >/dev/null; then
-        (sleep 0.1 && zellij action write-chars -- "$LAST_COMMAND" ) &
-        while true; do
-            echo "Send args to panels (ENTER for defaults, history C-r, C-c to exit):"
-            rlwrap -C lazysar $SCRIPT_PATH rlwrap || exit
-        done
-    else
-        (sleep 1 && zellij action write-chars -- "echo \"$LAST_COMMAND\" > $RUN_CMDS" ) &
-        $SHELL
-    fi
-    exit
+  shift
+  sleep 2
+  LAST_COMMAND=$(tail -1 "$RUN_CMDS")
+  trap stop_clients EXIT
+  if command -v rlwrap >/dev/null; then
+    (sleep 0.1 && zellij action write-chars -- "$LAST_COMMAND") &
+    while true; do
+      echo "Send args to panels (ENTER for defaults, history C-r, C-c to exit):"
+      rlwrap -C lazysar "$SCRIPT_PATH" rlwrap || exit
+    done
+  else
+    (sleep 1 && zellij action write-chars -- "echo \"$LAST_COMMAND\" > $RUN_CMDS") &
+    $SHELL
+  fi
+  exit
 fi
 
 if [ "$1" = "rlwrap" ]; then
-    shift
-    echo -n "> "
-    read COMMAND
-    if [ -z "$COMMAND" ]; then
-        COMMAND="$(cat "$DEFAULTS_FILE")"
-        echo "Using defaults from $DEFAULTS_FILE: $COMMAND"
-    fi
-    echo "$COMMAND" >> $RUN_CMDS
-    if [ "$COMMAND" = "STOP" ]; then
-        exit 1
-    fi
-    exit
+  shift
+  echo -n "> "
+  read -r COMMAND
+  if [ -z "$COMMAND" ]; then
+    COMMAND="$(cat "$DEFAULTS_FILE")"
+    echo "Using defaults from $DEFAULTS_FILE: $COMMAND"
+  fi
+  echo "$COMMAND" >>"$RUN_CMDS"
+  if [ "$COMMAND" = "STOP" ]; then
+    exit 1
+  fi
+  exit
 fi
 
 if [ ! -d "${SCRIPT_DIR}/.venv/bin" ]; then
-    echo "Python virtual environment not setup properly, did you run install.sh?"
-    exit 1
+  echo "Python virtual environment not setup properly, did you run install.sh?"
+  exit 1
 fi
 FORCE_COLOR=1 "${SCRIPT_DIR}/.venv/bin/python" "${SCRIPT_DIR}/lazysar.py" --presets-file="${PRESETS_FILE}" "$@"
